- name: Set up Maven
  run: mvn --version

- name: Build the project
  run: mvn clean package

- name: Extract Artifact Name
  id: artifact_name
  run: echo "ARTIFACT_NAME=$(mvn help:evaluate -Dexpression=artifactId -q -DforceStdout)-$(mvn help:evaluate -Dexpression=version -q -DforceStdout).jar" >> $GITHUB_ENV

- name: Deploy to EC2
  run: |
    ssh -i ~/.ssh/low2gostores.pem ubuntu@ec2-13-58-26-172.us-east-2.compute.amazonaws.com << 'EOF'
      # Kill existing Java processes
      ps aux | grep '[j]ava' | awk '{print $2}' | xargs sudo kill -9 || true
      echo "Old process killed"

      # Copy the built JAR file to EC2
      scp -i ~/.ssh/low2gostores.pem target/${{ env.ARTIFACT_NAME }} ubuntu@ec2-13-58-26-172.us-east-2.compute.amazonaws.com:/home/ubuntu/${{ env.ARTIFACT_NAME }}

      # Run the new application
      nohup java -jar -Dspring.profiles.active=local /home/ubuntu/${{ env.ARTIFACT_NAME }} > /home/ubuntu/app.log 2>&1 &
      echo $! > /home/ubuntu/app.pid
      echo "Application started with PID $(cat /home/ubuntu/app.pid)"
    EOF
