name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEV_EC2_PEM }}" > ~/.ssh/low2gostores.pem
          chmod 600 ~/.ssh/low2gostores.pem

      - name: Deploy to EC2
        run: |
          # Connect to EC2 and kill the previous Java process if running
          ssh -v -o StrictHostKeyChecking=no -i ~/.ssh/low2gostores.pem ubuntu@ec2-13-58-26-172.us-east-2.compute.amazonaws.com "pkill -f java || true"
          
          # Copy the built jar file to EC2
          scp -i ~/.ssh/low2gostores.pem target/app.jar ubuntu@ec2-13-58-26-172.us-east-2.compute.amazonaws.com:/home/ubuntu/app.jar
          
          # Restart the application
          ssh -i ~/.ssh/low2gostores.pem ubuntu@ec2-13-58-26-172.us-east-2.compute.amazonaws.com "nohup java -jar /home/ubuntu/app.jar &"
