name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEV_EC2_PEM }}" > ~/.ssh/low2gostores.pem
          chmod 600 ~/.ssh/low2gostores.pem

      - name: Build the Project
        run: |
          mvn clean package -Dmaven.test.skip=true
          echo "Build complete!"

      - name: Deploy to EC2
        run: |
          # Dynamically find the built JAR file
          JAR_FILE=$(ls target/l2g-backend-*.jar | head -n 1)
          echo "Deploying JAR file: $JAR_FILE"

          # Copy the new JAR file to the EC2 instance
          echo "Copying JAR file to EC2 instance"
          scp -i ~/.ssh/low2gostores.pem -o StrictHostKeyChecking=no "$JAR_FILE" ubuntu@ec2-13-58-26-172.us-east-2.compute.amazonaws.com:/home/ubuntu/test.jar

          # Execute SSH commands using tmux to detach the process
          ssh -v -o StrictHostKeyChecking=no -i ~/.ssh/low2gostores.pem ubuntu@ec2-13-58-26-172.us-east-2.compute.amazonaws.com << 'EOF'
            tmux new -d -s my_app

            tmux send-keys -t my_app "echo 'Killing existing Java processes'" ENTER
            tmux send-keys -t my_app "pids=$(ps aux | grep '[j]ava' | awk '{print $2}')" ENTER
            tmux send-keys -t my_app "if [ -n "\$pids" ]; then" ENTER
            tmux send-keys -t my_app "  echo 'Found Java processes: \$pids'" ENTER
            tmux send-keys -t my_app "  echo "\$pids" | xargs sudo kill -9 || true" ENTER
            tmux send-keys -t my_app "else" ENTER
            tmux send-keys -t my_app "  echo 'No Java processes found to kill'" ENTER
            tmux send-keys -t my_app "fi" ENTER

            tmux send-keys -t my_app "echo 'Starting the new application'" ENTER
            tmux send-keys -t my_app "nohup java -jar -Dspring.profiles.active=local /home/ubuntu/test.jar > /home/ubuntu/app_startup.log 2>&1 &" ENTER
            tmux send-keys -t my_app "sleep 5" ENTER
          
            # Verify if the process is running
            tmux send-keys -t my_app "if pgrep -f '/home/ubuntu/test.jar' > /dev/null; then" ENTER
            tmux send-keys -t my_app "  echo 'Application is running successfully'" ENTER
            tmux send-keys -t my_app "else" ENTER
            tmux send-keys -t my_app "  echo 'Application failed to start. Check logs at /home/ubuntu/app_startup.log'" ENTER
            tmux send-keys -t my_app "  exit 1" ENTER
            tmux send-keys -t my_app "fi" ENTER
          
            # Detach from the tmux session (optional)
            tmux detach -t my_app

            # Exit the SSH session
            exit
          EOF